### ISSUE TITLE
Doesn't work with 4.17

### ISSUE THREAD

**Issue by GeorgeR** [edsonsantoro/NWheeledPlugin#1]
Is it possible to update this plugin to work with 4.17?

**Comment by edsonsantoro** [comment]
I believe it's even easier to integrate this plugin on 4.17. As far as I know, Epic exported the vehicle manager class, which was private on early releases. This would make things easy to extend.

**Comment by manmohanbishnoi** [comment]
good to close this issue after merge of the pull request https://github.com/edsonsantoro/NWheeledPlugin/pull/2
